// Generated by CoffeeScript 1.3.3
(function() {
  var app;

  app = angular.module("xchglab", ['ui.bootstrap', "xchglabResourceHttp"], function($routeProvider) {
    $routeProvider.when("/list", {
      templateUrl: "list.html",
      controller: "ListCtrl",
      resolve: {
        users: function(User) {
          return User.all();
        }
      }
    });
    $routeProvider.when("/edit/:id", {
      templateUrl: "form.html",
      controller: "FormCtrl",
      resolve: {
        user: function(User, $route) {
          return User.getById($route.current.params.id);
        }
      }
    });
    $routeProvider.when("/new", {
      templateUrl: "form.html",
      controller: "FormCtrl",
      resolve: {
        user: function(User) {
          return new User();
        }
      }
    });
    return $routeProvider.otherwise({
      redirectTo: "/list"
    });
  });

  app.constant("XCHGLAB_CONFIG", {
    API_KEY: "CPRprCRzIbJ_GLKtT9eitH2knfZnzuRJ",
    DB_NAME: "of1"
  });

  app.factory("User", function($xchglabResourceHttp) {
    return $xchglabResourceHttp("users");
  });

  app.controller("ListCtrl", function($scope, $location, users) {
    try {
      $scope.users = users['_items'];
    } catch (error) {
      $scope.users = [];
    }
    $scope["new"] = function() {
      return $location.path("/new");
    };
    return $scope.edit = function(user) {
      return $location.path("/edit/" + user._id);
    };
  });

  app.controller("FormCtrl", function($scope, $location, user) {
    var changeError, changeSuccess, userCopy;
    userCopy = angular.copy(user);
    changeSuccess = function() {
      return $location.path("/list");
    };
    changeError = function() {
      throw new Error("Sth went wrong...");
    };
    $scope.user = user;
    $scope.post = function() {
      var actions;
      actions = {
        "$set": {
          "flds": {
            "uNam": user.uNam,
            "fNam": user.fNam,
            "lNam": user.lNam
          }
        }
      };
      return $scope.user.$put(JSON.stringify({
        "actions": actions
      }), changeSuccess, changeError);
    };
    $scope.save = function() {
      return $scope.user.$saveOrUpdate(changeSuccess, changeSuccess, changeError, changeError);
    };
    $scope.remove = function() {
      return $scope.user.$remove(changeSuccess, changeError);
    };
    $scope.abandonChanges = function() {
      return $location.path("/list");
    };
    return $scope.hasChanges = function() {
      return !angular.equals($scope.user, userCopy);
    };
  });

}).call(this);
