// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var $httpBackend;

  $httpBackend = void 0;

  describe("Services", function() {
    beforeEach(module("xchglab"));
    beforeEach(inject(function($injector) {
      var device, uri;

      uri = "http://localhost:3001/devices/50c61ff1d033a9b610000001";
      device = {
        name: "Light",
        updated_at: "2012-12-20T18:40:19Z"
      };
      $httpBackend = $injector.get("$httpBackend");
      return $httpBackend.whenGET(uri).respond(device);
    }));
    return describe("Device#get", function() {
      return it("returns a JSON", inject(function(Device) {
        var device;

        device = Device.get();
        $httpBackend.flush();
        return expect(device.name).toEqual("Light");
      }));
    });
  });

}).call(this);
