// Generated by CoffeeScript 1.6.2
(function() {
  app.constant("XCHGLAB_CONFIG", {
    API_KEY: "CPRprCRzIbJ_GLKtT9eitH2knfZnzuRJ",
    DB_NAME: "of1"
  });

  describe("xchglab resource", function() {
    beforeEach(module("xchglabResourceHttp"));
    beforeEach(inject(function($injector) {
      var $xchglabResourceHttp, XCHGLAB_CONFIG;

      $xchglabResourceHttp = $injector.get("$xchglabResourceHttp");
      return XCHGLAB_CONFIG = $injector.get("app.XCHGLAB_CONFIG");
    }));
    return describe("Testing", function() {
      it("getById", function() {
        return expect($xchglabResourceHttp.getById('51709ec7831c4b18ea866ef5')).toEqual(2);
      });
      return it("should add 2 + 2", function() {
        return expect(2).toEqual(2);
      });
    });
  });

}).call(this);
