// Generated by CoffeeScript 1.6.2
(function() {
  angular.module("test", ["xchglabResource"]).factory("User", function($xchglabResource) {
    return $xchglabResource("users");
  });

  describe("xchglab resource scenario", function() {
    return it("should add 2 + 2", function() {
      return expect(1 + 2).toEqual(3);
    });
  });

}).call(this);
