// Generated by CoffeeScript 1.6.2
(function() {
  describe("xchglab resource", function() {
    beforeEach(module("xchglabResourceHttp"));
    return describe("Testing", function() {
      it("getById", function() {
        return expect($xchglabResourceHttp.getById('51709ec7831c4b18ea866ef5')).toEqual(2);
      });
      return it("should add 2 + 2", function() {
        return expect(2).toEqual(2);
      });
    });
  });

}).call(this);
